# Generated by Django 5.0.2 on 2024-06-10 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.job_type'),
            preserve_default=False,
        ),
    ]
