# Generated by Django 5.0.2 on 2024-03-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=50)),
                ('Emp_phone', models.CharField(max_length=50)),
                ('Emp_email', models.CharField(max_length=50)),
                ('Emp_Address', models.CharField(max_length=500)),
                ('Emp_gender', models.CharField(max_length=50)),
                ('Emp_dob', models.DateField()),
                ('Emp_age', models.IntegerField()),
                ('Emp_location', models.CharField(max_length=50)),
                ('Emp_photo', models.ImageField(upload_to='employee/')),
                ('Emp_password', models.CharField(max_length=50)),
                ('location', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin_.location')),
            ],
            options={
                'db_table': 'employee_tb',
            },
        ),
    ]
