# Generated by Django 5.0.2 on 2024-06-12 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_', '0001_initial'),
        ('client', '0004_work_category'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worknumber', models.CharField(max_length=10)),
                ('status', models.CharField(default='Waiting', max_length=50)),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'appilications_tb',
            },
        ),
    ]
