# Generated by Django 5.0.2 on 2024-06-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_', '0002_applications'),
        ('client', '0004_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='Work',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='client.work'),
        ),
    ]
