# Generated by Django 5.0.2 on 2024-06-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_', '0003_applications_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='Work',
            new_name='work',
        ),
    ]
