# Generated by Django 5.0.2 on 2024-03-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_phone', models.CharField(max_length=50)),
                ('client_email', models.CharField(max_length=50)),
                ('client_Address', models.CharField(max_length=500)),
                ('client_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'client_tb',
            },
        ),
    ]
